version: "3"
services:
  nodeapp:
    container_name: node_pdf
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-webapp-network
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chuongnvt
      - MONGO_INITDB_ROOT_PASSWORD=chuongnvt
      - MONGO_INITDB_DATABASE=nestjs-auth-jwt
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge